version: 2

before:
    hooks:
        - go mod tidy

builds:
    - id: darwin-amd64
      main: ./cmd/flashback
      binary: flashback
      goos:
          - darwin
      goarch:
          - amd64
      env:
          - CC=o64-clang
          - CXX=o64-clang++
          - CGO_LDFLAGS=-ldl
      flags:
          - -mod=readonly
      ldflags:
          - -s -w -X main.version={{.Version}}
    - id: linux-amd64
      main: ./cmd/flashback
      binary: flashback
      goos:
          - linux
      goarch:
          - amd64
      env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
          - CGO_LDFLAGS=-ldl
      flags:
          - -mod=readonly
      ldflags:
          - -s -w -X main.version={{.Version}}
    - id: windows-amd64
      main: ./cmd/flashback
      binary: flashback
      goos:
          - windows
      goarch:
          - amd64
      env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
          - CGO_LDFLAGS=-ldl
      flags:
          - -mod=readonly
      ldflags:
          - -s -w -X main.version={{.Version}}
archives:
    - id: flashback
      ids:
          - darwin-amd64
          - linux-amd64
          - windows-amd64
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
      formats: ["zip"]
      wrap_in_directory: true
checksum:
    name_template: "checksums.txt"
snapshot:
    version_template: "{{ .Tag }}"
changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"

release:
    github:
        owner: yagnik-patel-47
        name: flashback
    prerelease: auto
    draft: false
